### ISSUE TITLE
Country names issues

### ISSUE THREAD

**Issue by gregbzh** [ralcr/Localizabler#32]
Hello, the function that find country names is not working properly.

Let me explain:

- in Countries.swift, line 19

let englishCountryName = (englishLocale as NSLocale).displayName(forKey: NSLocale.Key.countryCode, value: languageCode)

This function is displaying country name in english locale based on a country code (NSLocale.Key.countryCode) but **languageCode** is not necessary a country code. **languageCode** can be a localeIdentifier (fr-CH, en-NZ, en-CA...). 

In some cases it will find the right country (if country code and language code matches)
example: "lt-LT" it will display right country since Lithuania country code is same as Lithuanian language code (lt). Same for "pt-PT". 

But most of the time it won't find the country (or not the right one).

"fr-CH", "fr-MO" will return France instead of Switzerland and Monaco since the function is taking fr as country code.

A quick fix it to use the NSLocale.Key.identifier and parse the country.

```
let englishLocale = Locale.init(identifier :  "en_US")

let englishLanguageName = (englishLocale as NSLocale).displayName(forKey: NSLocale.Key.languageCode, value: languageCode)
var englishCountryName : String?

if let englishIdentifierName = (englishLocale as NSLocale).displayName(forKey: NSLocale.Key.identifier, value: languageCode) {
            englishCountryName = englishIdentifierName.slice(from: "(", to: ")")
}

return (languageName: englishLanguageName ?? "", countryName: englishCountryName ?? "")
```

```
extension String {

    func slice(from: String, to: String) -> String? {

        return (range(of: from)?.upperBound).flatMap { substringFrom in
            (range(of: to, range: substringFrom..<endIndex)?.lowerBound).map { substringTo in
                substring(with: substringFrom..<substringTo)
            }
        }
    }
}
```

**Comment by ralcr** [comment]
Thanks, i'll give it a try.

**Comment by cristibaluta** [comment]
This will be fixed in the next release. I choose to split the provided code into language and region and find their english name separately. That still can fail if the code does not contain the country, for example sv which should be swedish/Sweden it reports swedish/El Salvador, so i added some hardcoded values for most used countries too. https://github.com/ralcr/Localizable.strings/blob/60ccc7d993ba83c46fe0122151c4c87292e15a38/Localizabler/Countries.swift
